<div class="entry-edit layers slide-layers">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('etheme_slideshow')->__('Layers') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>
    <div id="slide_layers_container" class="box">
        <div id="slide_layers_container_top"></div>
        <?php echo $this->getLayersBoxHtml() ?>
    </div>
</div>

<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
</script>
