<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
    
    <?php $themeOptions = $this->helper('idstore');
    $baseUrl = $this->getBaseUrl();
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    ?>
    <?php /*
    <div class="mobile">
        <select id="mobile-menu" onchange="window.location = jQuery(this).val();">
        <option value="<?php echo $this->getBaseUrl() ?>"><?php echo $this->__('Home') ?></option>
        <?php echo $this->getChildHtml('mobile') ?>
        </select>
    </div>
    */
    ?>
        <div class="menu visible-desktop">
            <ul id="nav" class="menutype<?php echo $themeOptions->menuType(); ?>">
                <?php if ($home_link = $themeOptions->getHomeLink()) : ?>
                <li class="level0 level-top nav-0 <?php if($baseUrl == $currentUrl): ?>active<?php endif?>">
                    <a href="<?= $baseUrl ?>"><?= $home_link ?></a>
                </li>
                <?php endif ?>
                <?php echo $_menu ?>
	
	            <?php if ($block1 = $this->getChildHtml('nav_block1')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block1')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block2')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block2')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block3')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block3')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block4')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block4')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block5')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block5')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block6')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block6')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block7')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block7')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block8')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block8')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block9')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block9')->getTitle(); ?>
	            	<li class="level0 block_li parent">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?> 
	
	            <?php if ($block1 = $this->getChildHtml('nav_block10')): ?>
	                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block10')->getTitle(); ?>
	            	<li class="level0 block_li parent last_block">
	                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
	                    <div class="nav_block"><?php echo $block1; ?></div>
	                </li>
	    		<?php endif; ?>              
	        
	        
                <?php if ($addLink = $themeOptions->additionalLink()): ?>
                <li class="level0 additional level-top">
                    <a href="<?= $themeOptions->additionalLinkUrl() ?>"><?= $addLink ?></a>
                </li>
            <?php endif ?>
            </ul>

    </div>
<?php endif ?>