<script type="text/javascript">

//<![CDATA[
LayerTemplateText = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
            '<th class="type-text last"><?php echo Mage::helper('catalog')->__('Text') ?></th>'+
        '</tr>'+
            '<?php echo $this->getAppearanceSettings() ?>' +
        '<tr>'+
            '<td class="type-select">'+
                '<label for="slide_layer_{{option_id}}_animation">Animation: </label>'+
                '<?php echo $this->getAnimationSelect() ?>'+
            '</td>'+
        '</tr>'+
        '<tr>'+
            '<td class="type-select">'+
                '<label for="slide_layer_{{option_id}}_easing">Easing: </label>'+ 
                '<?php echo $this->getEasingSelect() ?>'+
            '</td>'+
        '</tr>'+
        '<tr>' +
            '<td class="type-select">' +
                '<label for="slide_layer_{{option_id}}_style">Style: </label>'+ 
                '<?php echo $this->getStyleSelect() ?>'+
            '</td>' +
        '</tr>' +
        '<tr>'+
            '<td class="type-textarea">'+
            '<textarea class="input-text" name="layers[{{option_id}}][text]" cols="25" rows="10">{{text}}</textarea>'+
            '</td>'+
        '</tr>'+
    '</table>';
if ($('option_panel_type_text')) {
    $('option_panel_type_text').remove();
}
//]]>
</script>