<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<?php $themeOptions = $this->helper('idstore') ?>
<?php $loggedClass = ($this->helper('customer')->isLoggedIn()) ? "in" : "out" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().' '.$themeOptions->getSiteLayout(). ' mobile-menutype-'. $themeOptions->mobileMenuType() . ' customer-logged-' . $loggedClass . '"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('revslider') ?>
        <div class="container main-container col1-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div class="row main">
                <div class="span12 col-main without-sidebar">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php if($themeOptions->backToTop() != 'disable'): ?>
<div id="back-to-top" class="btn-style-<?php echo $themeOptions->backToTop(); ?>"><a href="#top" id="top-link" ><span>Back to top</span></a></div>
<?php endif; ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
